account/urls.py
from django.urls import path 
from django.contrib.auth.views import LogoutView, LoginView
from .views import *


app_name = 'account'

urlpatterns = [
	path('', account, name='index'),
	path('manage/', list_user, name='list_user'),
	path('logout/', logout_page, name='logout'),
	path('login/', login_page, name='login'),
	path('create_user/', create_user, name='create_user'),
	path('delete_user/<int:pk>/', delete_user, name='delete_user'),
	path('update_user/<int:pk>/', update_user, name='update_user'),
]

cmu/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views



urlpatterns = [
	path('accounts/', include('account.urls', namespace='accounts')),
	path('', views.index, name='home'),
    path('admin/', admin.site.urls),
]

account/models.py
from django.db import models

account/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UpdateForm(forms.ModelForm):
	class Meta:
		model = User 
		field = ['username', 'first_name', 'last_name', 'email']
		exclude = ['password1', 'password2']

class LoginForm(forms.Form):
	class Meta:
		model = User
		fields = ['username', 'password']
		exclude = ['first_name', 'last_name', 'email']

class UserForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

account/views.py
from django.shortcuts import render, redirect 
from django.contrib.auth.models import User 
from django.contrib.auth import login, logout, authenticate
from django.http import HttpResponse
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from .forms import UserForm, LoginForm, UpdateForm


@login_required(login_url='accounts:login')
def account(request):
	return render(request, 'account/account.html',{})


def login_page(request):
	if request.method == 'POST':
		form = LoginForm(request.POST)
		if form.is_valid():
			username = request.POST['username']
			password = request.POST['password']
			user = authenticate(username=username, password=password)
			if user is not None:
				if user.is_superuser:
					login(request, user)
					next_url = request.GET.get('next')
					if next_url:
						return redirect(next_url)
					return redirect('accounts:index')

			else:
				messages.error(request,'Your account not admin')
	else:
		form = LoginForm()
	context = {'form':form}
	return render(request, 'account/login.html', context)


@login_required(login_url='accounts:login')
def logout_page(request):
	if request.method == 'POST':
		logout(request)
		return redirect('home')
	return render(request, 'account/logout.html',{})



@login_required(login_url='accounts:login')
def list_user(request):
	list_user = User.objects.all().exclude(username='admin')
	context = {'list_user':list_user}

	return render(request, 'account/list_user.html', context)
	

@login_required(login_url='accounts:login')
def create_user(request):
	if request.method == 'POST':
		form = UserForm(request.POST)
		if form.is_valid():
			form.save()
			messages.success(request, 'Account was created')
			return redirect('accounts:list_user')
		else:
			messages.error(request, 'Account not created')
	else:
		form = UserForm()
	return render(request, 'account/create_user.html', {'form':form})


@login_required(login_url='accounts:login')
def delete_user(request, pk):
	user = User.objects.get(pk=pk)
	if request.method == 'POST':
		user.delete()
		return redirect('accounts:list_user')
	return render(request, 'account/delete_user.html', {'user':user})


@login_required(login_url='accounts:login')
def update_user(request, pk):
	user = User.objects.get(pk=pk)
	form = UpdateForm(instance=user)
	if request.method == 'POST':
		form = UpdateForm(request.POST, instance=user)
		if form.is_valid():
			form.save()
			return redirect('accounts:list_user')

	context = {'form':form}
	return render(request, 'account/update_user.html', context)

cmu/views.py
from django.shortcuts import render

def index(request):
	return render(request, 'cmu/index.html',{})

templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>CMS</title>
	<link rel="stylesheet" type="text/css" href="{% static "bootstrap/bootstrap.min.css" %}">
</head>
<body>
	<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
		<div class="container">
			<a href="{% url 'home' %}" class="navbar-brand">CMS</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toglle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbar">
				<ul class="navbar-nav">

					{% if request.user.is_authenticated %}
					<li class="nav-item">
						<a href="{% url 'accounts:list_user' %}" class="nav-link active">Manage User</a>
					</li>
					<li class="nav-item">
						<a href="{% url 'accounts:logout' %}" class="nav-link active">Logout</a>
					</li>

					{% else %}
					<li class="nav-link">
						<a href="{% url 'accounts:login' %}" class="nav-link active">Login</a>
					</li>

					{% endif %}
				</ul>	
			</div>

		</div>
	</div>
</nav>





	{% block login_page_home %}
	
	{% endblock login_page_home %}

	{% block content %}

	{% endblock content %}


<script type="text/javascript" src="{% static "jquery/jquery.js" %}" ></script>
<script type="text/javascript" src="{% static "popper/popper.min.js" %}"></script>
<script type="text/javascript" src="{% static "bootstrap/bootstrap.min.js" %}"></script>

</body>
</html>

templates/cmu/index.html
{% extends "base/base.html" %}
{% block content %}
	<h2 class="text-center">Home</h2>
{% endblock content %}